# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00de0ad7a1883916c84f85437136dc82fb72472b2086dcbbf8489993220291ce4a69d5799f7ff28e435e10e276deb5027a915b12063d650440e8812f2e847c9

test:
  secret_key_base: 4c279574336ebc794178aa4f939f09b6832558252d98e84d012e787004f2db7f78b0c1d44e79dbc4bd1a5e5f565077a0032184966a3779cc4606b0cf22bb580d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
